# Generated by Django 5.1.1 on 2024-10-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(related_name='products', to='cart.cart'),
        ),
    ]
